#!/usr/bin/env python3
from camoufox.sync_api import Camoufox
from playwright.sync_api import TimeoutError as PlaywrightTimeoutError
import time
from os import makedirs, system
from getpass import getuser

def run(camoufox: Camoufox) -> None:
    global tmp_path

    browser = camoufox
    page = browser.new_page()

    page.goto("https://perchance.org/lemheealw3")

    frame = page.frame_locator("#outputIframeEl")
    style = frame.locator("select[data-name='artStyle']")
    shape = frame.locator("select[data-name='shape']")
    numbers = frame.locator("select[data-name='numImages']")

    def get_info(option, name) -> None:
        # 1. Warten bis das style existiert
        option.wait_for()

        # 2. Warten bis mehr als eine Option da ist (Polling, da FrameLocator kein wait_for_function kennt)
        for _ in range(50):  # max. ~10 Sekunden bei 0.2s Schritten
            count = option.locator("option").count()
            if count > 1:
                break
            time.sleep(0.2)
        else:
            raise TimeoutError(f"{option}-Optionen wurden nicht rechtzeitig geladen")

        # 3. Auslesen
        options = option.locator("option").evaluate_all(
            "elements => elements.map(e => e.text)"
        )

        with open(f"{tmp_path}/{name}.txt", "w") as f:
            f.write(str(options))

    get_info(style, "styles")
    get_info(shape, "shapes")
    get_info(numbers, "numbers")

if __name__ == "__main__":
    tmp_path = "/tmp/perchance_" + getuser()
    makedirs(tmp_path, exist_ok=True)
    system(f"chmod 2700 {tmp_path}")

    with Camoufox(humanize=True, headless=True, proxy={"server": "http://localhost:666"}) as camoufox:
        run(camoufox)